version: '3.6'
services:
  app:
    image: leonardpauli/docs-nginx-base:latest
    env_file: .env
    environment:
      server_default_local_proxy: docker.for.mac.localhost:8080
    ports: ["80:80", "443:443"]
    
    volumes:
      - ./data:/data
      - ./data/ssl/acme/webroot:/data/ssl/acme/webroot
      - ./data/ssl:/etc/nginx/ssl
      - ./nginx:/app-nginx/nginx
    depends_on:
      - ssl-manager
    networks:
      default:

  ssl-manager:
    image: leonardpauli/docs-ssl-manager:latest
    volumes: ["./data/ca:/data/ca", "./data/ssl:/data/ssl"]
    environment:
      ssl_prod_create: "$production"
      ssl_local_domains: "$server_default_local_domains"
      ssl_prod_domains: "$server_default_prod_domains"
      ssl_prod_notify_email: "$ssl_prod_notify_email"
      ssl_prod_stageing: "$ssl_prod_stageing"
      ssl_crt_created_log: "$ssl_crt_created_log"
      ssl_dhparam_create: "$ssl_dhparam_create"

networks:
  default:
