version: '3.6'
services:
  app:
    # ports: ["8080:8080"]
    environment:
      npm_config_registry: "http://verdaccio"
      server_default_local_proxy: http://0.0.0.0:8080
    command: sh -c "(cd /app-nginx && ./entrypoint.sh)"
    volumes:
      - ..:/app:delegated
      - ./data/node_modules:/app/node_modules:delegated
      - ~/.npm:/root/.npm:delegated
      - ./nginx:/app-nginx/nginx
    networks:
      verdaccio:

networks:
  verdaccio:
    external: true
    name: verdaccio
